#!/bin/bash

new_name=$1 #new name of directory and files

dir_name=$(basename $PWD) #name of template directory
full_path=$PWD #full path of template directory

echo $dir_name
echo $full_path

cd ../..

one_level_up=$PWD #full path of one level up
mkdir $new_name

cp -r $full_path $one_level_up #copy to two-levels up

# mv $dir_name $new_name #rename dir_name directory to new_name

# cd $new_name

# mv $dir_name.tex $new_name.tex

# vim $new_name.tex
