# Rebinding capslock to escape
setxkbmap -option "caps:escape"

# Toggle suspended program
stty susp undef
bind '"\C-z":"fg\015"'

# new latex templates:
function new_tex_simple() {
    cd ~/.vim/latex_templates/tex_template_simple
    ./new_tex "$1"
}

# vim server for vimtex:
function vtex() {
    vim --servername "$1" "$1"tex
}

# create python venv
function venvcreate() {
    python3 -m venv ~/.virtualenvs/"$1"
}

# activate python venv
function venvactivate() {
    source ~/.virtualenvs/"$1"/bin/activate
}

# tmux new session
function newmux(){
    tmux new -s $1
}

# tmux attach session
function attmux(){
    tmux attach-session -t $1
}

# tmux kill session
function killmux(){
    tmux kill-session -t $1
}

# tmux session with vim and IPython:
function vpmux() {
    dir_name=$PWD # get path of current directory
    cd ~/.vim/tmux_sessions
    ./tmux_sess_vimipython "$1" "$dir_name"
    tmux attach -t $1
    cd $dir_name # return to current directory so you're there when session is detached
}

# Run ls after cd
[ -z "$PS1" ] && return
function cd {
    builtin cd "$@" && ls -F
}
