#!/bin/bash

new_name=$1 #new name of directory and files

dir_name=$(basename $PWD) #name of template directory
full_path=$PWD #full path of template directory

cd ..

one_level_up=$PWD #full path of one level up

cp -R $full_path $one_level_up/$new_name #copy to two-levels up

cd $new_name

mv $dir_name.tex $new_name.tex

rm -rf new_tex

vim $new_name.tex
