#!/bin/bash

file_name=$1 #new name of directory and files

dir_name=$(basename $PWD) #name of directory
full_path=$PWD #full path of directory

cd ../..

two_levels_up=$PWD #full path of two levels up
mkdir $dir_name

cp -r $full_path $two_levels_up #copy to two-levels up

mv $dir_name $file_name #rename dir_name directory to file_name

cd $file_name

mv $dir_name.tex $file_name.tex

vim $file_name.tex
